# Generated by Django 5.0.7 on 2024-12-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_product_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='Owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
    ]
