# Generated by Django 5.0.7 on 2024-12-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_name_product_title_rename_owner_product_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
    ]
