# Generated by Django 5.0.7 on 2024-12-30 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_comment_productmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='ProductMember',
            new_name='ProjectMember',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='Product',
            new_name='Project',
        ),
    ]
